export const CATEGORIES = ['Interior', 'Exterior', 'Missing Paperwork', 'Possible Critical Issues']

export const SPACE_TYPES = [
  'Resident Room',
  'Resident Room Bathroom',
  'Therapy Room',
  'Lobby',
  'Main Entrance Vestibule',
  'Employee Lounge',
  'Janitor Closet',
  'Shower Room',
  'Housekeeping Room',
  'Dining Room',
  'Kitchen',
  'Conference Room',
  'Storage Room',
  'Staff Bathroom',
  'Public Bathroom',
  'Electrical Room',
  'Elevator Room',
  'Boiler Room',
  'Sprinkler Room',
  'Soiled Utility Room',
  'Medicine Room',
  'Salon Room',
  'Nourishment Room',
  'Clean Utility Room',
  'Corridor / Hallway',
  'Oxygen Closet',
  'Housekeeping Closet',
  'Maintenance Shop',
  'Generator Room',
]

export const INTERIOR_ISSUES = [
  'Repair Ceiling Tiles',
  'Install Missing Escutcheon',
  'Paint Wall',
  'Repair Hole in Wall',
  'Repair Missing Smoke Detector',
  'Repair Sink',
  'Repair Vanity',
  'Repair Damaged Wallpaper',
  'Repair Damaged Flooring',
  'Replace Missing Floor Tile',
  'Repair Damaged Baseboard',
  'Repair Damaged Door',
  'Replace Door Hardware / Lock',
  'Repair Damaged Window',
  'Repair Emergency Lighting',
  'Replace Exit Sign',
  'Repair Light Switch / Cover Plate',
  'Replace Missing Outlet Cover Plate',
  'Repair Exposed Wiring',
  'Repair Leaking Pipe',
  'Repair Toilet',
  'Install Missing Grab Bar',
  'Repair Handrail',
  'Repair Call Light / Pull Cord',
  'Repair Sprinkler Head',
  'Remove Plungers from Resident Rooms',
]

export const EXTERIOR_ISSUES = [
  'Repair Broken Fence',
  'Clean Roof Drains',
  'Clean Gutters',
]

export const CRITICAL_ISSUES = [
  'Scald Protection',
  'ADA Parking Issues',
  'Trees / Brush Touching Building',
  'ADA Bathroom Issues',
  'Dumpster Not on Concrete Pad',
]
